os:
  - linux

language: java
sudo: false
git:
  submodules: false

## ----------------------------------------------------------------------
## Build tools
## ----------------------------------------------------------------------


## ----------------------------------------------------------------------
## Perform build:
## ----------------------------------------------------------------------

script:

  - mvn clean install -DskipTests

after_success:
  - bash <(curl -s https://codecov.io/bash)

## ----------------------------------------------------------------------
## Notification
## ----------------------------------------------------------------------
notifications:
  email:
    recipients:
      - jiayu2@asu.edu
    on_success: always
    on_failure: always
