name: Scala Tests
on:
  - push
  - pull_request
jobs:
  CI:
    env:
      # It might crash with "java.lang.OutOfMemoryError: GC overhead limit exceeded" when loading italy PBF on GH
      # actions runners that have 7 GB of memory.
      MAVEN_OPTS: "-Xmx7g -Xms6g -XX:-UseGCOverheadLimit"

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install tools
        run: |
          sudo apt-get -y update && sudo apt-get -y install \
               wget \
               curl \
               zip \
               gdal-bin \
               osmium-tool \
               osmctools

      - name: Download Nord Ovest pbf
        run: mkdir -p src/test/resources/graphHopperSource && wget https://download.geofabrik.de/europe/italy/nord-ovest-latest.osm.pbf -O src/test/resources/graphHopperSource/nord-ovest-latest.osm.pbf

      - name: Download Nord Est pbf
        run: mkdir -p src/test/resources/graphHopperSource && wget https://download.geofabrik.de/europe/italy/nord-ovest-latest.osm.pbf -O src/test/resources/graphHopperSource/nord-est-latest.osm.pbf

      - name: Merge Nords pbf
        run: cd src/test/resources/graphHopperSource && osmium cat nord-ovest-latest.osm.pbf nord-est-latest.osm.pbf -o italy-latest.osm.pbf

      - name: Compile
        run: mvn --batch-mode --update-snapshots compile

      - name: Create Graph
        run: mvn exec:java -Dexec.mainClass=it.agilelab.bigdata.gis.core.apps.ConverterFromOSMToGraphHopperMap -Dexec.args="--graphLocation src/test/resources/graphHopper/ --osmLocation src/test/resources/graphHopperSource/italy-latest.osm.pbf"

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -Dtest='*,\!GraphHopperSpec*' test
