name: Scala Tests
on:
  - push
  - pull_request
jobs:
  CI:
    env:
      # It might crash with "java.lang.OutOfMemoryError: GC overhead limit exceeded" when loading italy PBF on GH
      # actions runners that have 7 GB of memory.
      MAVEN_OPTS: "-Xmx7g -Xms6g -XX:-UseGCOverheadLimit"

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.m2
          key: ${{ runner.os }}-sbt
      - uses: olafurpg/setup-scala@v10

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install wget
        run: sudo apt-get install wget

      - name: Download pbf
        run: mkdir -p src/test/resources/graphHopperSource && wget http://download.geofabrik.de/europe/italy-latest.osm.pbf -O src/test/resources/graphHopperSource/italy-latest.osm.pbf

      - name: Compile
        run: mvn --batch-mode --update-snapshots compile

      - name: Create Graph
        run: mvn exec:java -Dexec.mainClass=it.agilelab.bigdata.gis.core.apps.ConverterFromOSMToGraphHopperMap -Dexec.args="--graphLocation src/test/resources/graphHopper/ --osmLocation src/test/resources/graphHopperSource/italy-latest.osm.pbf"

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
