name: Scala Tests
on:
  push:
    branches: [ "master", "release/*" ]
  pull_request:
    branches: [ "master", "release/*" ]
jobs:
  unit-tests:
    env:
      JAVA_OPTS: "-Xmx6g -Xms6g"
      JVM_OPTS: "-Xmx6g -Xms6g"

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: sbt

      - name: Build and Test
        run: sbt -v "+testOnly -- -l org.scalatest.tags.Slow"
