name: Verify graph
on:
  push:
    branches: [ "master", "release/*" ]
  pull_request:
    branches: [ "master", "release/*" ]
jobs:
  verify-graph:
    env:
      MAVEN_OPTS: "-Xmx6g -Xms6g"

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Remove Graph Hopper directory
        run: rm -rf src/test/resources/graphHopper/

      - name: Compile
        run: mvn --batch-mode --update-snapshots compile

      - name: Create Graph
        run: ./hack/generate-graph.sh
